Гриды
htmlacademy-htmlcss/1434441-nerds-29 pull request #7
Opened 2020-10-06 04:48 UTC by sorokkamst

По разному сделал сетку.
Где-то пикселями, где-то fr, просто, чтобы потренироваться, думаю, что правильного решения просто нет.

Не понял, как сделать сетку для слайдера?

2020-10-06 16:58 UTC, andreysgra requested changes
В макете есть блоки, фоны которых упираются в края макета. Об их положении мы можем узнать из [этого пункта](https://up.htmlacademy.ru/htmlcss/29/project/nerds#nerds-3-1) ТЗ. Чтобы понять, как это реализовать, прочтите [эту статью](https://isqua.ru/blog/2016/06/23/content-po-sentru-fon-po-shirinie/).

2020-10-06 16:58 UTC, andreysgra commented on css/style.css
> +}
Странно, что стили для одного и того же элемента описаны в разных селекторах - `body` имеет класс `.page-body`. У вас есть стили для селектора тега `body` и класса `.page-body`. Логично их объединить вместе.

2020-10-06 16:58 UTC, andreysgra commented on css/style.css
> +  margin: 0 auto;
Задавать `width: 1160px` и `margin: 0 auto` тегу `body` не стоит. Для ограничения ширины контента и его центрирования нужно создать специальный класс, в который вынести необходимые свойства. Принцип создания такого контейнера можно увидеть в этом [шаге демо](https://up.htmlacademy.ru/htmlcss/29/demos/4619#16) (класс .container).

2020-10-06 16:58 UTC, andreysgra commented on css/style.css
> +  grid-template-columns: 360px 440px 360px;
Слишком много места отведено для логотипа и корзины. Контент в логотипе точно не будет увеличиваться, а вот в меню могу добавиться дополнительные пункты.

2020-10-06 16:58 UTC, andreysgra commented on css/style.css
> +  grid-template-columns: 1fr 1fr 1fr;
При таком шаблоне получается ширина одной колонки 320px

![image](https://user-images.githubusercontent.com/17790771/95232639-75ddcf80-080d-11eb-9f6e-bb1e46cc06fe.png)

а в макете оно составляет 300px. Происходит потому, что **1fr** относительная единица измерения, а справа от последнего блока есть свободное пространство 60px. Тут либо нужно задать в шаблоне размеры колонок в пикселах, либо (используя **fr**) добавить последнему блоку отступ справа.

2020-10-06 19:49 UTC, sorokkamst commented on css/style.css
> +  margin: 0 auto;
Почему для шапки в демо не задается контейнер. Заметил, что контейнер добавили только для main и footer.

2020-10-06 19:50 UTC, sorokkamst commented on css/style.css
> +  margin: 0 auto;
А так же, для чего задается это свойство - padding: 0 10px;

2020-10-07 04:50 UTC, sorokkamst commented
Забыл, что этот пулл реквест не был принят, сделал сетку для внутренней страницы.

2020-10-07 07:07 UTC, andreysgra commented on css/style.css
> +  margin: 0 auto;
>Почему для шапки в демо не задается контейнер? Заметил, что класс .container добавили только для main и footer, а шапку обернули в другую обертку.

Наверно этот вопрос нужно адресовать авторам курса. Мне тоже непонятна эта несвязанность - можно было класс `container` применять везде, где необходимо центрировать контент.

Что касается паддингов по краям - они нужны, чтобы контент сайта не прилипал к краям окна браузера на минимальной ширине сайта. В вашем макете паддинги составляют не 10px, а 20px. Об этом можно узнать из критерия [Б13](https://up.htmlacademy.ru/htmlcss/29/criteries#b13).

2020-10-07 07:24 UTC, andreysgra requested changes

2020-10-07 07:24 UTC, andreysgra commented on css/style.css
> +  padding: 0 10px;
```suggestion
  padding: 0 20px;
```

2020-10-07 07:24 UTC, andreysgra commented on css/style.css
>    background-color: var(--basic-grey);
Это свойство `background-color: var(--basic-grey);` перенесите в `main-header`.

2020-10-07 07:24 UTC, andreysgra commented on css/style.css
> +  grid-template-columns: 400px 1fr;
Здесь размеры несколько иные: **260px 760px** и расстояние между колонками (column-gap) 140px.

2020-10-07 07:24 UTC, andreysgra commented on css/style.css
>  }
Нужно задать расстояние между рядами (row-gap).

2020-10-07 07:24 UTC, andreysgra commented on catalog.html
>      <ul class="demos-search">
Этот блок логичнее перенести в секцию `demos`.

2020-10-07 11:57 UTC, merged